#!/usr/bin/bash
# Run all updater scripts
for _scr in $XDG_CONFIG_HOME/i3blocks/update/*
do
    _ins="$(/usr/bin/basename ${_scr})"
    case $1 in
        restart)
            /usr/bin/systemctl --user restart   i3blocks_socket@${_ins}.service ;;
        stop)
            /usr/bin/systemctl --user stop      i3blocks_socket@${_ins}.service ;;
        start)
            /usr/bin/systemctl --user is-active i3blocks_socket@${_ins}.service &&
            /usr/bin/systemctl --user restart   i3blocks_socket@${_ins}.service ||
            /usr/bin/systemctl --user start     i3blocks_socket@${_ins}.service ;;
        toggle)
            /usr/bin/systemctl --user is-active i3blocks_socket@${_ins}.service &&
            /usr/bin/systemctl --user stop      i3blocks_socket@${_ins}.service ||
            /usr/bin/systemctl --user start     i3blocks_socket@${_ins}.service ;;
    esac
done
