#!/usr/bin/bash
# Socket for deactivation
_socket=1
_file="/sys/class/backlight/${BRI_SCR}/brightness"
while : ; do
	[ -e "${_file}" ] || exit
	inotifywait --quiet "${_file}" > /dev/null
	pkill -RTMIN+"${_socket}" i3blocks ;
    sleep .1
done
