#!/usr/bin/bash
# Socket for deactivation
_socket=2
_ac="/sys/class/power_supply/AC0/online"
_ba="/sys/class/power_supply/BAT0/capacity"
while : ; do
	[ -e "${_ac}" ] || exit
	[ -e "${_ba}" ] || exit
	inotifywait --quiet "${_ac}" "${_ba}" > /dev/null
	pkill -RTMIN+"${_socket}" i3blocks ;
    sleep .1
done
