#!/usr/bin/bash
# Socket for deactivation
_socket=7
_file="${TASKDATA}"
while : ; do
	[ -e "${_file}" ] || exit
	inotifywait --quiet "${_file}" > /dev/null
	pkill -RTMIN+"${_socket}" i3blocks ;
    sleep 5
done
