#!/bin/dash
# vim:ft=sh

# Depends on: pactl, pamixer, (pavucontrol}

# Kill all descendents on exit
trap 'kill $(list_children $$) 2>/dev/null' INT QUIT KILL TERM PIPE

list_children () 
{
    local children=$(ps -o pid= --ppid "$1")
    for pid in $children
    do
        list_children "$pid"
    done
    echo "$children"
}

# Pulseaudio daemon
_left='pamixer --toggle-mute'
_right="pavucontrol & disown"
_up='pamixer --increase 1'
_down='pamixer --decrease 1'

get_text() {
    _sink="$(pactl info | sed -n 's|Default Sink: \(.*\)|\1|p')"
    _line="$(pactl list sinks short | grep -n "${_sink}" | cut -d : -f 1)"
    _defn="$(pactl list sinks | sed -n 's|^\sActive Port: \([^\s]*\)|\1|p' | sed -n "${_line}p")"
    _ismt="$(pactl list sinks | sed -n 's|^\sMute: \([^\s]*\)|\1|p' | sed -n "${_line}p")"
    _volm="$(pactl list sinks | sed -n 's|^\sVolume: \(.*\)$|\1|p' | sed -n "${_line}p" | awk '
        BEGIN{ RS=" "; vol=0; n=0; }
        /[0-9]+%$/ { n++; vol+=$1; }
        END{ if(n>0) { printf( "%.0f", vol/n ); } }' )"

    case "$_defn" in
        *hdmi*)                     _icon="﴿" ;;
        *headset*)                  _icon="" ;;
        *a2dp*)                     _icon="﫽" ;;
        *hifi*)                     _icon="﫛" ;;
        *headphone*)                _icon="" ;;
        *speaker*)                  _icon="蓼" ;;
        *network*)                  _icon="爵" ;;
        *analog*)                   _icon="" ;;
        *)                          _icon="" ;;
    esac

    if echo $_sink | grep -q 'bluez' ; then
        _suf=" "
    fi

    [ $_ismt = 'yes' ] && _ismt='true' || _ismt='false'

    _js="{ \"format\":\"${_volm}\", \"prefix\":\"${_icon} \", \"mute\":${_ismt}"
    _js="${_js}, \"suffix\":\"${_suf}\", \"on-click\":\"${_left}\""
    _js="${_js}, \"on-click-right\":\"${_right}\", \"on-scroll-up\":\"${_up}\""
    echo "${_js}, \"on-scroll-down\":\"${_down}\" }"
}

get_text
pactl subscribe 2>/dev/null | while read -r line ; do
    echo $line | grep -q -e "sink" -e "'change' on server #" && get_text
done
