#!/bin/dash

_dev="$(light -L | grep 'auto' | head -n 1 | awk '{$1=$1};1')"
_down="/usr/bin/light -Us ${_dev} 5 > /dev/null 2>&1"
_up="/usr/bin/light -As ${_dev} 5 > /dev/null 2>&1"

get_text () {
    _val="$(light -Gs "${_dev}" | sed 's|^\(.*\)\..*|\1|')" || exit 1
    if   [ "$_val" -ge 75 ] ; then
        _ico=""
    elif [ "$_val" -ge 50 ] ; then
        _ico=""
    else
        _ico=""
    fi
    _js="{ \"format\":\"${_val}\", \"prefix\":\"${_ico} \""
    echo "${_js},\"on-scroll-up\":\"${_up}\",\"on-scroll-down\":\"${_down}\"}"
}

get_text
/usr/bin/acpi_listen | while read -r line ; do
    echo $line | grep -q -e 'brightness' && get_text
done
