#!/bin/dash
# vim:ft=sh

# Depends on: khal, inotify

# Kill all descendents on exit
trap 'kill $(list_children $$) 2>/dev/null' INT QUIT KILL TERM PIPE

list_children () 
{
    local children=$(ps -o pid= --ppid "$1")
    for pid in $children
    do
        list_children "$pid"
    done
    echo "$children"
}

_file="${HOME}/Documents/Calendar"
_len=52

get_text () {
    _txt="$(khal list | head -n 1)"
    _mute='false'
    if [ "${_txt}" = "No events" ] ; then
        _mute='true'
    elif [ "${#_txt}" -gt "${_len}" ] ; then
        _txt="$(echo $_txt | awk '{print substr($0,1,'$_len'}')…"
    fi

    echo "{ \"format\":\"${_txt}\", \"mute\":${_mute}, \"prefix\":\" \" }"
}

while : ; do
    get_text
    sleep 5
    inotifywait -r -t -1 "${_file}" -e modify -e move -e create -e delete >/dev/null 2>&1 || break
done
