#!/bin/dash

# Kill all descendents on exit
trap 'kill $(list_children $$) 2>/dev/null' INT QUIT KILL TERM PIPE

list_children () 
{
    local children=$(ps -o pid= --ppid "$1")
    for pid in $children
    do
        list_children "$pid"
    done
    echo "$children"
}

while : ; do
    _txt="$(date '+%H:%M:%S')"
    echo "{ \"format\":\"$(date '+%H:%M:%S')\", \"prefix\":\" \" }"
    sleep 1
done
