#!/bin/dash


# Kill all descendents on exit
trap 'kill $(list_children $$) 2>/dev/null' INT QUIT KILL TERM PIPE HUP

list_children () 
{
    local children=$(ps -o pid= --ppid "$1")
    for pid in $children
    do
        list_children "$pid"
    done
    echo "$children"
}

_ico=""
_cpu1="$(grep 'cpu ' /proc/stat)"

while : ; do
    sleep 1
    _cpu2="$(grep 'cpu ' /proc/stat)"
    _per="$( echo "${_cpu1} ${_cpu2}" | awk '{ printf( "%.2f", ($13-$2+$15-$4)*100/($13-$2+$15-$4+$16-$5)) }' )"
    _cpu1="${_cpu2}"
    echo "{ \"format\":\"${_per}\", \"prefix\":\"${_ico} \" }"
done
