#!/bin/dash

get_icon () {
    case "$1" in
        0)  _out="" ;; 1)  _out="" ;; 2)  _out="" ;; 3)  _out="" ;;
        4)  _out="" ;; 5)  _out="" ;; 6)  _out="" ;; 7)  _out="" ;;
        8)  _out="" ;; 9)  _out="" ;; 10) _out="" ;; 11) _out="" ;;
        12) _out="" ;; 13) _out="" ;; 14) _out="" ;; 15) _out="" ;;
        16) _out="" ;; 18) _out="" ;; 19) _out="" ;; 20) _out="" ;;
        21) _out="" ;; 22) _out="" ;; 23) _out="" ;; 24) _out="" ;;
        25) _out="" ;; 26) _out="" ;; 27) _out="" ;; 28) _out="" ;;
        29) _out="" ;; 30) _out="" ;;
    esac
    echo "$(echo -n $_out | awk '{print substr($0,length,1)}')"
    #echo "$(echo -n $_out | awk '{print substr($0,1,1)}')"
}

while : ; do
    _moon="$(echo "$(printf "%.0f" "$(echo "scale=2; ( $(date -d "00:00" +%s) - $(date -d "1999-08-11" +%s) )/(60*60*24)" | bc)") % 29.530588853" | bc | awk '{printf("%d",$1+.5)}')"
    echo "{ \"format\":\"$(date '+%a %d, %b %Y')\", \"prefix\": \" \", \"suffix\":\" $(get_icon $_moon)\" }"
    sleep "$(( $(date -d "tomorrow 0" +%s) - $(date +%s) + 5 ))"
done
