#!/bin/dash

# Kill all descendents on exit
trap 'kill $(list_children $(cut -d " " -f4 < /proc/self/stat)) 2>/dev/null; exit' INT QUIT KILL TERM PIPE HUP

list_children () 
{
    children=$(ps -o pid= --ppid "$1")
    for pid in $children
    do
        list_children "$pid"
    done
    echo "$children"
}

_icr=""
_ich=""

get_text () {
    _rfs="$(df -hPl /      | tail -1 | awk '{ printf $3 "/" $2 " (" $5 ")" }' )"
    _hfs="$(df -hPl /home/ | tail -1 | awk '{ printf $3 "/" $2 " (" $5 ")" }' )"
    echo "{ \"format\":\"${_rfs}  ${_hfs}\", \"prefix\":\"${_icr} \", \"suffix\":\" ${_ich}\" }"
}

while : ; do
    get_text
    sleep 60
done

get_loop
