#!/bin/dash

_file="${HOME}/Documents/Mail/Gmail/Inbox/new"

get_text () {
    _new="$(find $HOME/Documents/Mail/Gmail/Inbox/new | wc -l)"
    if [ "$_new" -le 0 ] ; then
        _ico=""
        _new="0"
        _mute='true'
    else
        _ico=""
        _new="${_new}"
        _mute='false'
    fi
    echo "{ \"format\":\"${_new}\", \"mute\":${_mute}, \"prefix\":\"${_ico} \" }"
}

while : ; do
    get_text
    sleep 5
    inotifywait -t -1 -r "${_file}" -e modify -e move -e create -e delete >/dev/null 2>&1 || break
done
