#!/bin/dash
# Read this better

# Depends on lm_sensors

# Kill all descendents on exit
trap 'kill $(list_children $(cut -d " " -f4 < /proc/self/stat)) 2>/dev/null; exit' INT QUIT KILL TERM PIPE HUP

list_children () 
{
    children=$(ps -o pid= --ppid "$1")
    for pid in $children
    do
        list_children "$pid"
    done
    echo "$children"
}

case "$(hostname)" in
    sbp-homestation)
        get_text () {
            exit
        } ;;
    sbp-workstation)
        get_text () {
            _spe="$(sensors | grep -i 'fan' | awk '{print $2}' | tr '\n' ',' |
              sed 's|.$||')"
            echo "{ \"format\":\"${_spe}\", \"prefix\":\" \" }"
        } ;;
    sbp-laptop)
        get_text () {
            exit
        } ;;
    sbp-server)
        get_text () {
            exit
        } ;;
esac

while : ; do
    get_text
    sleep 2
done
