#!/bin/dash
# Read this better

# Depends on lm_sensors

# Kill all descendents on exit
trap 'kill $(list_children $(cut -d " " -f4 < /proc/self/stat)) 2>/dev/null; exit' INT QUIT KILL TERM PIPE HUP

list_children () 
{
    children=$(ps -o pid= --ppid "$1")
    for pid in $children
    do
        list_children "$pid"
    done
    echo "$children"
}

get_text () {
    if [ $(hostname) = 'sbplaptop' ] ; then
        # Can't read this
        exit
    elif [ $(hostname) = 'sbpnotebook' ] ; then
        _spe="$(sensors | grep -i 'fan' | awk '{print $2}' | tr '\n' ',')"
        _spe="${_spe::-1}"
    else
        _spe="$(sensors | grep -i 'fan' | awk '{print $3}' | tr '\n' ',')"
        _spe="${_spe::-1}"
    fi

    echo "{ \"format\":\"${_spe}\", \"prefix\":\" \" }"

}

while : ; do
    get_text
    sleep 2
done
