#!/bin/dash

_dev="$(light -L | grep 'kbd' | head -n 1 | awk '{$1=$1};1')"
_x11_left="/usr/bin/xkb-switch -n >/dev/null 2>&1"
_down="/usr/bin/light -Urs ${_dev} 5 >/dev/null 2>&1"
_up="/usr/bin/light -Ars ${_dev} 1 >/dev/null 2>&1"

get_light () {
    # Get backlight levels
    _bri="$(light -Gs "${_dev}" | awk '{printf("%d",$0);}')"
    if   [ "$_bri" -gt 66 ] ; then
        echo " "
    elif [ "$_bri" -gt 33 ] ; then
        echo " "
    elif [ "$_bri" -gt 0 ] ; then
        echo " "
    else
        echo ""
    fi

}

get_text_x11 () {
    # Get keymap
    _sta="$(xkb-switch -p)"
    _lan="$(echo "${_sta}" | sed 's|\(.*\)(.*)|\1|' | awk '{print toupper($0)}')"
    _lay="$(echo "${_sta}" | grep '(' | sed 's|.*(\(.*\))|\1|')"
    if [ -z "${_lay}" ] ; then
        _lay="qwe"
    else
        _lay="$(echo "${_lay}" | awk '{print substr($0,1,3)}')"
    fi
    _suf="$(get_light)"
    _js="{\"format\":\"${_lan}(${_lay})\", \"prefix\":\" \", \"suffix\":\"${_suf}\""
    _js="${_js}, \"on-scroll-down\":\"${_down}\", \"on-scroll-up\":\"${_up}\""
    echo "${_js}, \"on-click\":\"${_x11_left}\" }"
}

get_text_sway () {
    # Get suffix
    _suf="$(get_light)"

    # Get keymap
    _map="$(swaymsg -t get_inputs | jq '.[] | select(.name | test(".*[K,k]eyboard.*")) | select(.type == "keyboard") | .xkb_active_layout_name' | tail -n 1)"

    # Parse the map
    _txt="$(echo "${_map}" | sed 's|"\([a-z,A-Z]*\) (\([a-z,A-Z]*\))"|\1 \2|g')"
    _txt="$(echo "${_txt}" | awk '{printf("%s(%s)", toupper(substr($1,1,3)), tolower(substr($2,1,3)));}')"

    # Print results
    _js="{\"format\":\"${_txt}\", \"prefix\":\" \", \"suffix\":\"${_suf}\""
    echo "${_js}, \"on-scroll-down\":\"${_down}\", \"on-scroll-up\":\"${_up}\" }"
}

blight () {
    if [ "${XDG_SESSION_TYPE}" = 'x11' ] ; then
        /usr/bin/acpi_listen | while read -r line ; do
            sleep .1
            echo $line | grep -q -e 'kbd' && get_text_x11
        done
    elif [ "${XDG_SESSION_TYPE}" = 'wayland' ] ; then
        if [ ! -z "${SWAYSOCK}" ] ; then
            /usr/bin/acpi_listen | while read -r line ; do
                sleep .1
                echo $line | grep -q -e 'kbd' && get_text_sway
            done
        fi
    fi
}

keymaps () {
    if [ "${XDG_SESSION_TYPE}" = 'x11' ] ; then
        get_text_x11
        /usr/bin/xkb-switch -W | while read -r line ; do
            get_text_x11
        done
    elif [ "${XDG_SESSION_TYPE}" = 'wayland' ] ; then
        if [ ! -z "${SWAYSOCK}" ] ; then
            get_text_sway
            swaymsg -t subscribe '["input"]' -m | while read -r line; do
                if [ "$(echo "${line}" | jq '.change' -r)" = 'xkb_layout' ] ; then
                    get_text_sway
                fi
            done
        fi
    fi
}

blight & keymaps
