#!/bin/dash

_dev="$(light -L | grep 'kbd' | head -n 1 | awk '{$1=$1};1')"
_left="/usr/bin/xkb-switch -n >/dev/null 2>&1"
_down="/usr/bin/light -Urs ${_dev} 5 >/dev/null 2>&1"
_up="/usr/bin/light -Ars ${_dev} 1 >/dev/null 2>&1"

get_text () {
    # Get backlight levels
    _bri="$(light -Gs "${_dev}" | awk '{printf("%d",$0);}')"
    if   [ "$_bri" -gt 66 ] ; then
        _suf=" "
    elif [ "$_bri" -gt 33 ] ; then
        _suf=" "
    elif [ "$_bri" -gt 0 ] ; then
        _suf=" "
    else
        _suf=""
    fi
    # Get keymap
    _ico=""
    _sta="$(xkb-switch -p)"
    _lan="$(echo "${_sta}" | sed 's|\(.*\)(.*)|\1|' | awk '{print toupper($0)}')"
    _lay="$(echo "${_sta}" | grep '(' | sed 's|.*(\(.*\))|\1|')"
    if [ -z "${_lay}" ] ; then
        _lay="qwe"
    else
        _lay="$(echo "${_lay}" | awk '{print substr($0,1,3)}')"
    fi

    _js="{ "
    _js="${_js}  \"format\":\"${_lan}(${_lay})\""
    _js="${_js}, \"prefix\":\"${_ico} \""
    _js="${_js}, \"suffix\":\"${_suf}\""
    _js="${_js}, \"on-click-left\":\"${_left}\""
    _js="${_js}, \"on-scroll-up\":\"${_up}\""
    _js="${_js}, \"on-scroll-down\":\"${_down}\""
    _js="${_js} }"
    echo "${_js}"
}

blight () {
    /usr/bin/acpi_listen | while read -r line ; do
        sleep .1
        echo $line | grep -q -e 'kbd' && get_text
    done
}

keymaps () {
    /usr/bin/xkb-switch -W | while read -r line ; do
        get_text
    done
}

get_text
blight & keymaps
