#!/bin/dash

# Depends on: 

# Kill all descendents on exit
trap 'kill $(list_children $(cut -d " " -f4 < /proc/self/stat)) 2>/dev/null; exit' INT QUIT KILL TERM PIPE HUP

list_children () 
{
    children=$(ps -o pid= --ppid "$1")
    for pid in $children
    do
        list_children "$pid"
    done
    echo "$children"
}

_int="broadcast"

get_text () {
    if [ -e "/sys/class/net/${_int}" ] ; then
        _stat="$(cat "/sys/class/net/${_int}/operstate")"
        if [ "${_stat}" = 'down' ] ; then
            echo '{ "format": "", "mute": true, "prefix": " "}'
        else
            _ip="$(ip addr show "${_int}" | awk '/inet / {print $2}' | sed 's|\(.*\)\/.*|\1|g')"
            echo "{ \"format\":\"${_ip}\", \"mute\": false, \"prefix\":\" \" }"
        fi
    else
        echo '{ "format": "", "mute": true, "prefix": ""}'
    fi
}

get_text
ip monitor | while read line; do
    if echo $line | grep -q "${_int}" && [ "$_time" != "$(date +%s)" ]; then
        get_text
        _time="$(date +%s)"
    fi
done
