#!/bin/dash
_ico=""
_file="${HOME}/Documents/RSS"

# Depends on: newsboat

# Kill all descendents on exit
trap 'kill $(list_children $$) 2>/dev/null' INT QUIT KILL TERM PIPE

list_children () 
{
    local children=$(ps -o pid= --ppid "$1")
    for pid in $children
    do
        list_children "$pid"
    done
    echo "$children"
}

get_text () {
    _txt="$(newsboat -x print-unread | awk '{ print $1 }')"
    if echo "${_txt}" | grep -q "Error:" ; then
        _txt=""
        _mute="true"
    elif [ "${_txt}" = '0' ] ; then
        _mute="true"
    else
        _mute='false'
    fi

    echo "{ \"format\":\"${_txt}\", \"prefix\":\"${_ico} \", \"mute\":${_mute} }"
}

while : ; do
    get_text
    sleep 5
    inotifywait -t -1 -r "${_file}" -e modify -e move -e create -e delete >/dev/null 2>&1 || break
done
