#!/bin/env python
"""
Formatting wrapper around system monitoring daemons
"""

import argparse
import json
import re
import sys
import subprocess

# Status bar colors: base16-default-dark
COLOR = {
    'base00': '181818',
    'base01': '282828',
    'base02': '383838',
    'base03': '585858',
    'base04': 'b8b8b8',
    'base05': 'd8d8d8',
    'base06': 'e8e8e8',
    'base07': 'f8f8f8',
    'base08': 'ab4642',
    'base09': 'dc9656',
    'base0A': 'f7ca88',
    'base0B': 'a1b56c',
    'base0C': '86c1b9',
    'base0D': '7cafc2',
    'base0E': 'ba8baf',
    'base0F': 'a16946'
}

class Memoize:
    """ Decorator to memoize function calls """
    def __init__(self, fn):
        self.fun = fn
        self.memo = {}

    def __call__(self, *args):
        if args not in self.memo:
            self.memo[args] = self.fun(*args)
        return self.memo[args]

@Memoize
def get_color(inp):
    """ Function to return a color string """
    # Define the colors as given by base16, and by their names
    named = {
        'background': COLOR['base01'],
        'bkg': COLOR['base01'],
        'muted': COLOR['base03'],
        'mute': COLOR['base03'],
        'foreground': COLOR['base04'],
        'frg': COLOR['base04'],
        'red': COLOR['base08'],
        'crimson': COLOR['base08'],
        'ora': COLOR['base09'],
        'orange': COLOR['base09'],
        'yel': COLOR['base0A'],
        'yellow': COLOR['base0A'],
        'gre': COLOR['base0B'],
        'green': COLOR['base0B'],
        'cya': COLOR['base0C'],
        'cyan': COLOR['base0C'],
        'ind': COLOR['base0D'],
        'blue': COLOR['base0D'],
        'indigo': COLOR['base0D'],
        'vio': COLOR['base0E'],
        'pink': COLOR['base0E'],
        'violet': COLOR['base0E'],
        'purple': COLOR['base0E'],
        'bro': COLOR['base0F'],
        'brown': COLOR['base0F']}
    colors = {**COLOR, **named}
    # Do answer checking
    if re.search(r'^(?:[0-9a-fA-F]{3}){1,2}$', inp):
        return inp
    if inp in colors:
        return colors[inp]
    if re.search(r'^#(?:[0-9a-fA-F]{3}){1,2}$', inp):
        return inp
    print('Invalid color selection, defaulting to red')
    return colors['red']

if __name__ == '__main__':
    # Parse inputs
    PRSR = argparse.ArgumentParser('Modules to print system info')

    PRSR.add_argument('-c', '--color', help="Specify accent color")
    PRSR.add_argument('name', help="Daemon name to run", type=str)
    NSPC = PRSR.parse_args()

    # Get requested method
    METHOD = vars(NSPC)['name']

    # Get color
    ACCENT = get_color(vars(NSPC)['color'])

    # Create formatting string
    TEXT = '%{{A1:{on-click}: A2:{on-click-middle}: A3:{on-click-right}: '
    TEXT += 'A4:{on-scroll-up}: A5:{on-scroll-down}:}}%{{u#{accent} +u o#{accent} +o}}'
    TEXT += '%{{F#{accent}}}{prefix}%{{F-}}'
    TEXT += '%{{F#{color}}}{format}%{{F-}}'
    TEXT += '%{{F#{accent}}}{suffix}%{{F-}}%{{-u u- -o o-}}%{{A A A A A}}'

    # Create formatting dict
    FORM = {'format': '',
            'prefix': '',
            'suffix': '',
            'accent': ACCENT,
            'color': get_color('frg'),
            'on-click' : 'true',
            'on-click-right' : 'true',
            'on-click-middle' : 'true',
            'on-scroll-up' : 'true',
            'on-scroll-down' : 'true',
            'mute': False}

    # Start the daemon
    DAEMON = subprocess.Popen(sys.path[0] + '/' + METHOD,
                              stdout=subprocess.PIPE,
                              stderr=subprocess.DEVNULL)
    while True:
        # Read all lines as json until termination
        LINE = DAEMON.stdout.readline()
        # Exit if terminated
        if not LINE:
            break
        # Read input
        NEW = json.loads(LINE.decode('utf-8'))
        # Load onto the formatting dict
        FORM = {**FORM, **NEW}
        # If both the prefix and format are empty, skip
        if FORM['prefix'] == '' and FORM['suffix'] == '' and FORM['format'] == '':
            print('')
            sys.stdout.flush()
            continue
        # Overwrite color depending on muting
        if FORM['mute']:
            FORM['color'] = get_color('mute')
        else:
            FORM['color'] = get_color('frg')
        # Redo accent color
        FORM['accent'] = get_color(FORM['accent'])
        # Correct lemonbar tags
        FORM['on-click'] = FORM['on-click'].replace(':', r'\:')
        FORM['on-click-right'] = FORM['on-click-right'].replace(':', r'\:')
        FORM['on-click-middle'] = FORM['on-click-middle'].replace(':', r'\:')
        FORM['on-scroll-up'] = FORM['on-scroll-up'].replace(':', r'\:')
        FORM['on-scroll-down'] = FORM['on-scroll-down'].replace(':', r'\:')
        # Print formatted string
        print(TEXT.format_map(FORM))
        # Flush stdout
        sys.stdout.flush()
