#!/bin/dash
# Fix later

# Depends on: sensors

# Kill all descendents on exit
trap 'kill $(list_children $$) 2>/dev/null' INT QUIT KILL TERM PIPE HUP

list_children () 
{
    local children=$(ps -o pid= --ppid "$1")
    for pid in $children
    do
        list_children "$pid"
    done
    echo "$children"
}

_cel="糖"

get_text () {
    if [ $(hostname) = 'sbplaptop' ] ; then
        _tmp="$(sensors | grep 'Tdie:'      | awk '{print $2}' | sed 's/+\(.*\)°C/\1/')"
    elif [ $(hostname) = 'sbpnotebook' ] ; then
        _tmp="$(sensors | grep 'Package id' | awk '{print $4}' | sed 's/+\(.*\)°C/\1/')"
    else
        return
    fi

    _txt="${_tmp}${_cel}"

    # Do integer check
    _sto="$(echo ${_tmp} | awk '{ printf( "%d", $1 ); }')"
    if [ "${_sto}" -gt 75 ] ; then
        _ico=""
    elif [ "${_sto}" -gt 65 ] ; then
        _ico=""
    elif [ "${_sto}" -gt 55 ] ; then
        _ico=""
    elif [ "${_sto}" -gt 45 ] ; then
        _ico=""
    else
        _ico=""
    fi

    case $_format in
        pango|i3|i3blocks|sway)
            json_output "<span color='${_col}'>${_ico}</span> ${_txt}" ;;
        lemonbar|polybar|bspwm)
            echo "%{u${_col}}%{+u}%{F${_col}}${_ico}%{F-} ${_txt}%{-u}%{u-}" ;;
    esac
}

get_loop () {
    while : ; do
        get_text
        sleep 1
    done
}

get_loop
