#!/bin/dash

# Depends on: todoman

# Kill all descendents on exit
trap 'kill $(list_children $(cut -d " " -f4 < /proc/self/stat)) 2>/dev/null; exit' INT QUIT KILL TERM PIPE HUP

list_children () 
{
    children=$(ps -o pid= --ppid "$1")
    for pid in $children
    do
        list_children "$pid"
    done
    echo "$children"
}

_ico="省"
_len=32
_file="${HOME}/Documents/Todo"

get_text () {
    _txt="$(todo --porcelain list --sort priority | jq -r '.[0]."summary"')"
    _mute='false'
    if [ "$_txt" = 'null' ] ; then
        _txt='No tasks'
        _mute='true'
    elif [ "${#_txt}" -gt "${_len}" ] ; then
        _txt="$(echo $_txt | awk '{print substr($0,1,'$_len'}')…"
    fi

    echo "{ \"format\":\"${_txt}\", \"prefix\":\"${_ico} \", \"mute\":${_mute} }"
}

while : ; do
    get_text
    sleep 5
    inotifywait -r -t -1 "${_file}" -e modify -e move -e create -e delete >/dev/null 2>&1 || break
done
