#!/bin/dash

_ic1="⏼"
_ic2=""

get_text () {
    _txt="$(uptime --pretty | sed 's/up //' | sed 's/\ years\?,/y/' | sed 's/\ weeks\?,/w/' | sed 's/\ days\?,/d/' | sed 's/\ hours\?,\?/h/' | sed 's/\ minutes\?/m/')"
    _usr="$(uptime | sed 's|.*\([0-9][0-9]*\)\suser.*|\1|')"

    echo "{ \"format\":\"${_txt}${_usr}\", \"prefix\":\"${_ic1} \", \"suffix\":\" ${_ic2}\" }"
}

while : ; do
    get_text
    sleep 60
done
