#!/bin/sh

# Turn off system beep
xset -b

# Fix missing mouse pointer issues
xsetroot -cursor_name left_ptr

# Xresources
for file in "/etc/X11/Xresources" "$XDG_CONFIG_HOME/X11/resources"; do
    if [ -f "$file" ]; then
        echo "Loading resource: $file"
        xrdb -merge "$file"
    fi
done

# Xmodmap
for file in "/etc/X11/Xkbmap" "$XDG_CONFIG_HOME/X11/keymap"; do
    if [ -f "$file" ]; then
        echo "Loading keymap: $file"
        setxkbmap `cat "$file"`
        XKB_IN_USE=yes
    fi
done

# Load xmodmap if not using XKB
if [ -z "$XKB_IN_USE" ]; then
    for file in "/etc/X11/Xmodmap" "$XDG_CONFIG_HOME/X11/modmap"; do
        if [ -f "$file" ]; then
           echo "Loading modmap: $file"
           xmodmap "$file"
        fi
    done
fi

unset XKB_IN_USE

# Run all system xinitrc shell scripts
xinitdir="/etc/X11/xinit/xinitrc.d"
if [ -d "$xinitdir" ]; then
    for script in $xinitdir/*; do
        echo "Loading xinit script $script"
        if [ -x "$script" -a ! -d "$script" ]; then
            . "$script"
        fi
    done
fi

# Start i3
exec $XDG_CONFIG_HOME/i3/launcher.sh
