#!/usr/bin/sh

# Copied mostly from https://www.lukeshu.com/blog/x11-systemd.html

# Check if XDG_RUNTIME_DIR is set, and fail otherwise
if [ -z "$XDG_RUNTIME_DIR" ]; then
    printf "XDG_RUNTIME_DIR isn't set\n" >&2
    exit 6
fi

# Turn off system beep
xset -b

# This is to fix the xdg_gnome_session stuff from crashing
dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY

# Fix missing mouse pointer issues
xsetroot -cursor_name left_ptr

# Pipe name
_fifo="${XDG_RUNTIME_DIR}/x11-wm@${DISPLAY}"

# Make sure the FIFO gets removed if killed early
trap "rm -f ${_fifo}" EXIT

# Open the named pipe
mkfifo "${_fifo}"

# Keep this part open until those that open the pipe are terminated
cat < "${_fifo}" &
systemctl --user start "X11@${DISPLAY}.target" &
wait
systemctl --user stop "X11@${DISPLAY}.target"

# Clear the FIFO pipe for further usage
rm -f "${_fifo}"
