#!/usr/bin/sh

# BSPWM rules
bspc config border_width                2
bspc config window_gap                  12
bspc config merge_overlapping_monitors  true
bspc config split_ratio                 0.52
bspc config borderless_monocle          true
bspc config gapless_monocle             true

# Monitor icon names
ws1=""
ws2="爵"
ws3=""
ws4=""
ws5=""
ws6=""
ws7=""
ws8=""
ws9=""
ws0="漣"

# Refresh monitors
M=$(bspc query -M | wc -l)
if [[ "$M" == 1 ]]; then
    bspc monitor --reset-desktops $ws1 $ws2 $ws3 $ws4 $ws5 $ws6 $ws7 $ws8 $ws9 $ws0
elif [[ "$M" == 2 ]]; then
    bspc monitor $(bspc query --monitors|awk NR==1) --reset-desktops $ws1 $ws2 $ws3 $ws4 $ws5
    bspc monitor $(bspc query --monitors|awk NR==2) --reset-desktops $ws6 $ws7 $ws8 $ws9 $ws0
elif [[ "$M" == 3 ]]; then
    bspc monitor $(bspc query --monitors|awk NR==1) --reset-desktops $ws1 $ws2 $ws3 $ws4
    bspc monitor $(bspc query --monitors|awk NR==2) --reset-desktops $ws5 $ws6 $ws7
    bspc monitor $(bspc query --monitors|awk NR==3) --reset-desktops $ws8 $ws9 $ws0
else
    I=1
    for monitor in $(bspc query -M); do
        bspc monitor $monitor -n "$I" -d $I
        let I++
    done
fi

if [ -z "$BSPWM_RULE_SET" ] ; then
    BSPWM_RULE_SET=yes
    bspc rule --add Termite:dropdown sticky=on state=floating hidden=on
    # First desktop: Communication
    bspc rule --add Skype               desktop="$ws1"
    bspc rule --add Rambox              desktop="$ws1"
    bspc rule --add Qemu-system-x86_64  desktop="$ws1"
    bspc rule --add org.remmina.Remmina desktop="$ws1"
    bspc rule --add Thunar              desktop="$ws1"
    # Second desktop: Internet
    bspc rule --add qutebrowser         desktop="$ws2"
    bspc rule --add Firefox             desktop="$ws2"
    # Third desktop: Terminal
    bspc rule --add Termite             desktop="$ws3"
    bspc rule --add kitty               desktop="$ws3"
    # Fourth desktop: Science
    bspc desktop 4 --layout monocle
    bspc rule --add MATLAB*             desktop="$ws4"
    bspc rule --add 'GNU Octave'        desktop="$ws4"
    bspc rule --add Spyder              desktop="$ws4"
    # Fifth desktop: Reading
    bspc rule --add Zathura             desktop="$ws5" state=tiled
    bspc rule --add Evince              desktop="$ws5"
    # Sixth desktop: Writing
    bspc rule --add libreoffice*        desktop="$ws6"
    bspc rule --add Soffice             desktop="$ws6"
    # Seventh desktop: Media
    bspc rule --add mpv                 desktop="$ws7"
    bspc rule --add smplayer            desktop="$ws7"
    bspc rule --add cantata             desktop="$ws7"
    bspc rule --add vlc                 desktop="$ws7"
    # Eighth desktop: Image
    bspc rule --add pdfsam              desktop="$ws8"
    bspc rule --add Gimp*               desktop="$ws8"
    bspc rule --add inkscape            desktop="$ws8"
    bspc rule --add Blender             desktop="$ws8"
    bspc rule --add openscad            desktop="$ws8"
    bspc rule --add Ristretto           desktop="$ws8"
    # Ninth desktop: Games
    bspc rule --add Steam               desktop="$ws9"
    bspc rule --add Stepmania           desktop="$ws9"
    # Tenth desktop: Settings
    bspc rule --add Pavucontrol         desktop="$ws0"
    bspc rule --add 'Syncthing GTK'     desktop="$ws0"
    bspc rule --add QDBusViewer         desktop="$ws0"
    bspc rule --add Pamac-updater       desktop="$ws0"
    bspc rule --add Pamac-manager       desktop="$ws0"
fi

# Autostart programs
dex --autostart --environment bspwm &

# Set cursor
xsetroot -cursor_name left_ptr
