#!/bin/sh

#wid=$1
#class=$2
#instance=$3
#monitor=$4
#destop=$5
#node=$6
fwid=$(bspc query -N -n focused.automatic)

if [ -n "$fwid" ] ; then
	wattr wh $fwid | {
		read width height
		if [ $width -gt $height ] ; then
			echo "split_dir=west"
		else
			echo "split_dir=south"
		fi
		echo "split_ratio=0.5"
	}
fi
