#!/usr/bin/bash

# Socket for deactivation
_socket=2

# If running, just leave yourself be
[ "$(pgrep -x i3mpdupdate | wc -l)" -gt 2 ] && exit

while : ; do
	pgrep -x mpd || exit
	mpc idle > /dev/null
	pkill -RTMIN+"${_socket}" i3blocks ;
done
