#!/bin/bash

# This script reloads all polybar instances
case "${XDG_CURRENT_DESKTOP}" in
    bspwm)
        (
            flock 200
            killall --quiet polybar
            # Wait until graceful exit
            while pgrep -u $UID -x polybar > /dev/null; do sleep 0.5; done
            # Get outputs from bspwm
            bspc query --names --monitors | while read m; do
                POLYMON=$m polybar --reload top </dev/null >/var/tmp/polybar-$m.log 2>&1 200>&- & disown
                POLYMON=$m polybar --reload bot </dev/null >/var/tmp/polybar-$m.log 2>&1 200>&- & disown
            done
        ) 200>/var/tmp/polybar-launch.lock
        ;;
    *)
        true
        ;;
esac
