#!/bin/bash
# Copies archlive to /tmp and generates iso

# Error handling
set -uo pipefail
trap 's=$?; echo "$0: Error on line "$LINENO": $BASH_COMMAND"; exit $s' ERR

# To work with variables
_usr="$(users)"
_cur="$(pwd)"
_fol="${_cur}/$(dirname "${0}")/../archlive"
_dir='/tmp/archlive'
_iso="${1:-"${HOME}/Downloads"}"
if [ -f "${_iso}" ] ; then
    echo "(makearchiso)==> Invalid argument..."
    exit
fi

# Clean directories
[ -d "${_dir}" ] && sudo rm -rf "${_dir}"
[ -d "${_iso}" ] && (echo "(makearchiso)==> Old iso, deleting...";rm -rf "${_iso}")

# Copy files and change owner
echo "(makearchiso)==> Copying to ${_dir} and making owner root..."
cp -r "${_fol}" "${_dir}"
cp -r "${HOME}/.config/xfce4" "${_dir}/airootfs/etc/skel/.config/"
cp -r "${HOME}/.config/arch/bin/installer" "${_dir}/airootfs/etc/skel/"
sudo chown -R root:root "${_dir}"

# Change directory and build
echo "(makearchiso)==> Starting build..."
cd "${_dir}"
sudo ./build.sh -v
cd "${_cur}"

# Change iso file
sudo chown -R "${_usr}:${_usr}" "${_dir}/out"
