#!/bin/bash

# This script generates a tmux session with htop, music visualizer and ncmpcpp

SESSIONNAME=MusicControl
tmux has-session -t $SESSIONNAME &> /dev/null

if [ $? != 0 ]
then
    tmux new-session -s $SESSIONNAME -d 'htop'
    tmux split-window -h -p 75 'ncmpcpp --screen visualizer'
    tmux split-window -v -p 62 'ncmpcpp --screen playlist'
fi

tmux -2 attach-session -t $SESSIONNAME
