#!/bin/bash
# Script to change the fun variable of UNDERTALE
# Load the fun variable
FUN=$1

# Where the game files are
INIF=$XDG_CONFIG_HOME/UNDERTALE/undertale.ini
DATF=$XDG_CONFIG_HOME/UNDERTALE/file0

# Change the game files
sed -i "s/\(fun=\"\)\([0-9][0-9]*\)\(\.0*\"\)/\1${FUN}\3/" $INIF
sed -i "36s/.*/${FUN}/" $DATF
