# Set XDG_CONFIG_HOME
export XDG_CONFIG_HOME="$HOME/.config"

# Import Path
[ -d "$HOME/.local/bin" ] && PATH="$HOME/.local/bin:$PATH"
[ -d "$XDG_CONFIG_HOME/scripts" ] && PATH="$XDG_CONFIG_HOME/scripts:$PATH"
# import vim-live-latex
if [ -d "$XDG_CONFIG_HOME/nvim/bundle/vim-live-latex-preview/bin" ]
then
    PATH="$XDG_CONFIG_HOME/nvim/bundle/vim-live-latex-preview/bin:$PATH"
fi

# Z directory
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
# ZIM stuff
export ZIM_HOME="$ZDOTDIR/zimfw"

# GPG public key
export GPGKEY=0B7151C823559DD8A7A04CE36426139E2F4C6CCE
# Password store location
export PASSWORD_STORE_DIR=$HOME/.pass
export PASSWORD_STORE_GIT=$HOME/.pass

# Compile in parallel using AUR
export MAKEFLAGS="-j$(nproc)"

# Just MATLAB things
# One day . . . one day MATLAB will actually do what I want it to do . . .
export MATLAB_DIR=/opt/matlab
export MATLAB_LOG_DIR="~/.cache/matlab/"
# export MATLAB_JAVA=/usr/lib/jvm/java-8-openjdk/jre
export LD_PRELOAD="/usr/lib/libstdc++.so:/usr/lib/libfreetype.so.6"
# export LD_LIBRARY_PATH=/usr/lib/xorg/modules/dri/

# Monitors
if [[ $(hostname) == 'sbplaptop' ]]
then
    export MON_0="eDP"
    export BRI_SCR="amdgpu_bl0"
    export BRI_KBD="asus::kbd_backlight"
elif [[ $(hostname) == 'sbpworkstation' ]]
then
    export MON_0="DP-2"
    export BRI_SCR=""
    export BRI_KBD=""
elif [[ $(hostname) == 'sbphomestation' ]]
then
    export MON_0="eDP-1"
    export BRI_SCR=""
    export BRI_KBD=""
fi

# GPG config
export GNUPGHOME=$XDG_CONFIG_HOME/gnupg
# QT5 theme
export QT_STYLE_OVERRIDE="gtk2"
export QT_QPA_PLATFORMTHEME="gtk2"
# Set neovim as editor
export EDITOR=/usr/bin/nvim
# Set qutebrowser as browser
export BROWSER=/usr/bin/qutebrowser
# Set terminal to use for launching
export TERMINAL=/usr/bin/termite
# Notmuch
export NOTMUCH_CONFIG=$XDG_CONFIG_HOME/neomutt/notmuch-config
# OpenFOAM
export FOAM_INST_DIR=/opt/OpenFOAM
# Weechat
export WEECHAT_HOME=$XDG_CONFIG_HOME/weechat
# Taskwarrior
export TASKRC=$XDG_CONFIG_HOME/taskrc
export TASKDATA=$HOME/Documents/Tasks/
export TIMEWARRIORDB=$HOME/Documents/Tasks/

# Systemctl things
load_variables_systemd () {
    /usr/bin/systemctl --user set-environment XDG_CONFIG_HOME=$XDG_CONFIG_HOME
    /usr/bin/systemctl --user set-environment PATH=$PATH
    /usr/bin/systemctl --user set-environment PASSWORD_STORE_GIT=$PASSWORD_STORE_GIT
    /usr/bin/systemctl --user set-environment PASSWORD_STORE_DIR=$PASSWORD_STORE_DIR
    /usr/bin/systemctl --user set-environment BRI_SCR=$BRI_SCR
    /usr/bin/systemctl --user set-environment BRI_KBD=$BRI_KBD
    /usr/bin/systemctl --user set-environment GNUPGHOME=$GNUPGHOME
    /usr/bin/systemctl --user set-environment QT_STYLE_OVERRIDE=$QT_STYLE_OVERRIDE
    /usr/bin/systemctl --user set-environment QT_QPA_PLATFORMTHEME=$QT_QPA_PLATFORMTHEME
    /usr/bin/systemctl --user set-environment EDITOR=$EDITOR
    /usr/bin/systemctl --user set-environment BROWSER=$BROWSER
    /usr/bin/systemctl --user set-environment TERMINAL=$TERMINAL
    /usr/bin/systemctl --user set-environment NOTMUCH_CONFIG=$NOTMUCH_CONFIG
    /usr/bin/systemctl --user set-environment WEECHAT_HOME=$WEECHAT_HOME
    /usr/bin/systemctl --user set-environment TASKRC=$TASKRC
    /usr/bin/systemctl --user set-environment TASKDATA=$TASKDATA
    /usr/bin/systemctl --user set-environment TIMEWARRIORDB=$TIMEWARRIORDB
}
# load_variables_systemd
