# Used for setting user's interactive shell configuration and executing commands,
# will be read when starting as an interactive shell.

# User configuration
export HIST_STAMPS="dd/mm/yyyy"
export HISTFILE="${XDG_DATA_HOME}/zsh/history"
setopt HIST_IGNORE_ALL_DUPS

# SSH agent
unset SSH_AGENT_PID
if [ "${gnupg_SSH_AUTH_SOCK_by:-0}" -ne $$ ]; then
  export SSH_AUTH_SOCK="$(gpgconf --list-dirs agent-ssh-socket)"
fi

# Bash completion in zsh
autoload bashcompinit
bashcompinit -d "${XDG_CACHE_HOME}/zsh"

gitsync () {
    [ -z "${1}" ] && $1="$(pwd)"
    git -C $1 pull
    git -C $1 add -A
    git -C $1 commit -m "Auto-sync: $(date +%Y-%m-%d_%H:%M:%S)"
    git -C $1 push
}

wttr_weather () {
    if [ -z "${1}" ]
    then
        curl 'https://wttr.in/?w'
    else
        curl 'https://wttr.in/'"$(echo $1)"
    fi
}

# Aliases
alias config='git -C $XDG_CONFIG_HOME'
alias config-sync='gitsync $XDG_CONFIG_HOME'
alias py='bpython'
alias vim='nvim'
alias mutt='neomutt'
alias ofoam="source ${FOAM_INST_DIR}/OpenFOAM-5.0/etc/bashrc"
alias ncmpc='ncmpcpp --screen playlist --slave-screen visualizer'

# ZIM settings
# Remove path separator from WORDCHARS.
WORDCHARS=${WORDCHARS//[\/]}
# Set a custom path for the completion dump file.
zstyle ':zim:completion' dumpfile "${XDG_CACHE_HOME}/zsh/zcompdump-${ZSH_VERSION}"
# Set a custom terminal title format using prompt expansion escape sequences.
# See http://zsh.sourceforge.net/Doc/Release/Prompt-Expansion.html#Simple-Prompt-Escapes
# If none is provided, the default '%n@%m: %~' is used.
zstyle ':zim:termtitle' format '%1~'
# Set what highlighters will be used.
# See https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/docs/highlighters.md
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets cursor)
#zinput_mode='vi'
# Customize the main highlighter styles.
# See https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/docs/highlighters/main.md#how-to-tweak-it
#typeset -A ZSH_HIGHLIGHT_STYLES
#ZSH_HIGHLIGHT_STYLES[comment]='fg=10'

# Initialize modules
if [[ ${ZIM_HOME}/init.zsh -ot ${ZDOTDIR:-${HOME}}/.zimrc ]]; then
  # Update static initialization script if it's outdated, before sourcing it
  source ${ZIM_HOME}/zimfw.zsh init -q
fi
source ${ZIM_HOME}/init.zsh

# Post-init module configuration

# Set editor default keymap to emacs (`-e`) or vi (`-v`)
bindkey -v
# Bind ^[[A/^[[B manually so up/down works both before and after zle-line-init
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down
# Bind up and down keys
zmodload -F zsh/terminfo +p:terminfo
if [[ -n ${terminfo[kcuu1]} && -n ${terminfo[kcud1]} ]]; then
  bindkey ${terminfo[kcuu1]} history-substring-search-up
  bindkey ${terminfo[kcud1]} history-substring-search-down
fi
bindkey '^P' history-substring-search-up
bindkey '^N' history-substring-search-down
bindkey -M vicmd 'k' history-substring-search-up
bindkey -M vicmd 'j' history-substring-search-down

# Prompt
zprompt_theme='powerlevel10k'
if tty | grep -q tty; then
    # TTY default to the text theme
    [[ -f "${ZDOTDIR}/p10k.text.zsh" ]] && source "${ZDOTDIR}/p10k.text.zsh"
else
    # To customize prompt, run `p10k configure` or edit ~/.config/zsh/p10k.zsh
    [[ -f "${ZDOTDIR}/p10k.icon.zsh" ]] && source "${ZDOTDIR}/p10k.icon.zsh"
fi
